// Action types for fetching weather 

export const FETCH_WEATHER_INFO = 'FETCH_WEATHER_INFO';
export const ERROR_FETCH_WEATHER_INFO = 'ERROR_FETCH_WEATHER_INFO';
export const SUCCESS_FETCH_WEATHER = 'SUCCESS_FETCH_WEATHER';
export const REMOVE_FETCH_RESPONSE = 'REMOVE_FETCH_RESPONSE';
